### ISSUE TITLE
How to generate own textual_label_embedding?

### ISSUE THREAD

**Issue by HoYinTam** [xinyu1205/Recognize_Anything-Tag2Text#27]
Hello, thank you for your great work! 

I am trying to implement zero-shot inference myself. But I have no idea about the textual label embeding generation. I have tested a few model like "openai/clip-vit-large-patch14", "openai/clip-vit-base-patch32", "laion/CLIP-ViT-B-16-laion2B-s34B-b88K", "laion/CLIP-ViT-H-14-laion2B-s32B-b79K". But I fail to reproduce the embedding of "ram_tag_list". 

P.s.  When will zero-shot inference open-source?

**Comment by xinyu1205** [comment]
Thanks for your attention! I am doing my best to open source zero-shot inference code today.

**Comment by xinyu1205** [comment]
@HoYinTam Hi, I just open source zero-shot inference code, welcome to try out based on README.md and provide any feedback.

**Comment by HoYinTam** [comment]
Wow！Many thanks for your great support!. Everything is fine except some small bug in the result format. The model output is something like 
![image](https://github.com/xinyu1205/Recognize_Anything-Tag2Text/assets/9464454/372d78a9-1478-4800-8b4e-4f1b8ae146b8)
When it takes the index 0, it only return the first letter.
![image](https://github.com/xinyu1205/Recognize_Anything-Tag2Text/assets/9464454/eac4d278-d5bc-4486-a47f-ccd0288b7187)

**Comment by xinyu1205** [comment]
Thanks for the response, I have fixed this bug.

**Comment by kippapollo** [comment]
@HoYinTam @xinyu1205 Thanks for open source for zero shot.
Which is zero-shot inference code?

**Comment by ntlm1686** [comment]
> Thanks for your attention! I am doing my best to open source zero-shot inference code today.

Hi, could you please explain how is the frozen_tag_embedding derived? Which model is used to produce these embeddings?
