### ISSUE TITLE
请问会出量化模型吗？

### ISSUE THREAD

**Issue by onexuan** [xinyu1205/Recognize_Anything-Tag2Text#8]
请问会出量化模型吗？

**Comment by xinyu1205** [comment]
您好，目前没有打算出更小模型的打算。不过我们两周内会开一个更强大的模型，若有兴趣欢迎关注~

**Comment by onexuan** [comment]
期待

**Comment by onexuan** [comment]
@xinyu1205 再加个rest api 吧

**Comment by xinyu1205** [comment]
> @xinyu1205 这个太强了，这几天测试一些图片，准确很高，caption tags会支持中文？昨晚还加了个rest api

我们近期发布了一个更强的模型，The Recognize Anything Model，后续会公开相关模型和推理代码。
以及，欢迎你把简洁使用TAg2Text的rest api的代码共享出来，成为本项目的贡献者之一。

**Comment by onexuan** [comment]
我第一次写python代码，有点不敢，看几个项目凑出rest api，能运行，能出json

**Comment by mrbulb** [comment]
@xinyu1205 同样想问一下caption tags之后会支持中文吗？如果不支持是否有计划release训练代码，我们可以在中文数据集上微调一下。

**Comment by xinyu1205** [comment]
> @xinyu1205 同样想问一下caption tags之后会支持中文吗？如果不支持是否有计划release训练代码，我们可以在中文数据集上微调一下。

目前的RAM支持同时输出中英文tags，欢迎试用~

**Comment by xinyu1205** [comment]
> @xinyu1205 同样想问一下caption tags之后会支持中文吗？如果不支持是否有计划release训练代码，我们可以在中文数据集上微调一下。

训练代码会尽快在几周内公开
